const ROPSTEN = 'ropsten'
const RINKEBY = 'rinkeby'
const KOVAN = 'kovan'
const MAINNET = 'mainnet'
const LOCALHOST = 'localhost'
const CLASSIC = 'classic'
const CALLISTO = 'callisto'
const LEEP = 'leep'
const LEEPTEST = 'leeptest'

const MAINNET_CODE = 1
const ROPSTEN_CODE = 3
const RINKEBY_CODE = 4
const KOVAN_CODE = 42
const CLASSIC_CODE = 61
const CALLISTO_CODE = 820
const LEEP_CODE = 1
const LEEPTEST_CODE = 1

const ROPSTEN_DISPLAY_NAME = 'Ropsten'
const RINKEBY_DISPLAY_NAME = 'Rinkeby'
const KOVAN_DISPLAY_NAME = 'Kovan'
const MAINNET_DISPLAY_NAME = 'Main Ethereum Network'
const CLASSIC_DISPLAY_NAME = 'Ethereum Classic'
const CALLISTO_DISPLAY_NAME = 'Callisto'
const LEEP_DISPLAY_NAME = 'Leep Network'
const LEEPTEST_DISPLAY_NAME = 'Leep Test Network'

module.exports = {
  ROPSTEN,
  RINKEBY,
  KOVAN,
  MAINNET,
  CLASSIC,
  LEEP,
  LEEPTEST,
  LOCALHOST,
  MAINNET_CODE,
  ROPSTEN_CODE,
  RINKEBY_CODE,
  KOVAN_CODE,
  CLASSIC_CODE,
  LEEP_CODE,
  LEEPTEST_CODE,
  ROPSTEN_DISPLAY_NAME,
  RINKEBY_DISPLAY_NAME,
  KOVAN_DISPLAY_NAME,
  MAINNET_DISPLAY_NAME,
  CLASSIC_DISPLAY_NAME,
  LEEP_DISPLAY_NAME,
  LEEPTEST_DISPLAY_NAME,
  CALLISTO,
  CALLISTO_CODE,
  CALLISTO_DISPLAY_NAME,
}
