const {
  ROPSTEN,
  RINKEBY,
  KOVAN,
  MAINNET,
  CLASSIC,
  CALLISTO,
  LEEP,
  LEEPTEST,
  ROPSTEN_CODE,
  RINKEBY_CODE,
  KOVAN_CODE,
  CLASSIC_CODE,
  CALLISTO_CODE,
  LEEP_CODE,
  LEEPTEST_CODE,
  ROPSTEN_DISPLAY_NAME,
  RINKEBY_DISPLAY_NAME,
  KOVAN_DISPLAY_NAME,
  MAINNET_DISPLAY_NAME,
  CLASSIC_DISPLAY_NAME,
  CALLISTO_DISPLAY_NAME,
  LEEP_DISPLAY_NAME,
  LEEPTEST_DISPLAY_NAME,
} = require('./enums')

const networkToTypeMap = {
  [CLASSIC_CODE]: CLASSIC,
  [CALLISTO_CODE]: CALLISTO,
  [LEEP_CODE]: LEEP,
  [LEEPTEST_CODE]: LEEPTEST,
}


const networkToNameMap = {
  [ROPSTEN]: ROPSTEN_DISPLAY_NAME,
  [RINKEBY]: RINKEBY_DISPLAY_NAME,
  [KOVAN]: KOVAN_DISPLAY_NAME,
  [MAINNET]: MAINNET_DISPLAY_NAME,
  [CLASSIC]: CLASSIC_DISPLAY_NAME,
  [CALLISTO]: CALLISTO_DISPLAY_NAME,
  [LEEP]: LEEP_DISPLAY_NAME,
  [LEEPTEST]: LEEPTEST_DISPLAY_NAME,
  [ROPSTEN_CODE]: ROPSTEN_DISPLAY_NAME,
  [RINKEBY_CODE]: RINKEBY_DISPLAY_NAME,
  [KOVAN_CODE]: KOVAN_DISPLAY_NAME,
  [CLASSIC_CODE]: CLASSIC_DISPLAY_NAME,
  [CALLISTO_CODE]: CALLISTO_DISPLAY_NAME,
  [LEEP_CODE]: LEEP_DISPLAY_NAME,
  [LEEPTEST_CODE]: LEEPTEST_DISPLAY_NAME,
}

const getNetworkDisplayName = key => networkToNameMap[key]

const getNetworkTypeFromCode = key => networkToTypeMap[key]

module.exports = {
  getNetworkDisplayName,
  getNetworkTypeFromCode,
}
